# Generated by Django 6.0.3 on 2026-04-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Classical', 'Classical'), ('Jazz', 'Jazz'), ('RandB', 'R&B'), ('Country', 'Country')], max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='occasion',
            field=models.CharField(choices=[('Party', 'Party'), ('Study', 'Study'), ('Relax', 'Relax'), ('Work', 'Work'), ('Workout', 'Workout'), ('Sleep', 'Sleep')], max_length=20),
        ),
    ]
